### ISSUE TITLE
Little typo ?

### ISSUE THREAD

**Issue by tigerblue77** [dm-vdo/vdo#46] opened 2022-04-24 14:27 UTC
Hello there,

I'm compiling VDO for use on Debian 11.3 (kernel 5.10.0-3) using the following command :

```bash
git clone https://github.com/dm-vdo/vdo.git /tmp/vdo/ && \
cd /tmp/vdo/ && \
make -j$(nproc)
```

And got this little echo error :

![image](https://user-images.githubusercontent.com/37409593/164981083-97b2f3b5-e960-4580-a273-af441afcb633.png)

which comes from `utils/vdo/Makefile:116`

![image](https://user-images.githubusercontent.com/37409593/164981231-ef488a7e-b675-4465-9139-1aad3d10b2a0.png)

I'm not a bash expert but, why is this double "$$" ? And this line ?
Apparently, my compiler doesn't like it, but it compiles well.

Have a nice day,

**Comment by lorelei-sakai** [comment] 2022-05-03 00:11
Thank you for reporting this. It is indeed a typo. It will be fixed in the next update.

The line is merely informational, so you can ignore it. As you noted, it does not affect the compilation.

**Comment by tigerblue77** [comment] 2022-05-03 10:06
You're welcome, thanks for your reply.

So will you remove the entire line or only replace the "$$" by "$" ?
Out of curiosity, was there a reason for "$$"?

**Comment by lorelei-sakai** [comment] 2022-05-05 02:17
I was going to just fix the typo, but on reflection the extra output isn't very useful, so I will remove it.

The $$ appears to have been a simple typo, nothing more. $$ has a meaning in makefiles, but it doesn't make any sense here.

**Comment by tigerblue77** [comment] 2022-05-05 09:20
I do agree, thanks for the detailed explanation.
Have a nice day

**Comment by tigerblue77** [comment] 2022-12-19 22:04
Hello @lorelei-sakai,
Is this issue fixed now ? If yes, feel free to close it :)

**Comment by slegendr** [comment] 2022-12-20 13:46
Hello @tigerblue77 ,
I have confirmed that the issue is fixed.  Thank you for your attention to detail and for reporting it.  :)

**Closed by slegendr** 2022-12-20 13:46 UTC
